// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNPxJs4KhmlCwNAtwSazeZQEwHd584bqs',
    appId: '1:804475636661:web:f6d2dc869cb1aad067a7fc',
    messagingSenderId: '804475636661',
    projectId: 'apd-junior',
    authDomain: 'apd-junior.firebaseapp.com',
    storageBucket: 'apd-junior.firebasestorage.app',
    measurementId: 'G-FH940LCB1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmbwYQwTZf3yC1TyIy4M5T37V6BwR9r78',
    appId: '1:804475636661:android:24bf7146c166a9bf67a7fc',
    messagingSenderId: '804475636661',
    projectId: 'apd-junior',
    storageBucket: 'apd-junior.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIZBV9Guv0GVqW9-8K6XDBafuZKkGaq4',
    appId: '1:804475636661:ios:9b82cc319f01cceb67a7fc',
    messagingSenderId: '804475636661',
    projectId: 'apd-junior',
    storageBucket: 'apd-junior.firebasestorage.app',
    iosBundleId: 'com.example.kidsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNPxJs4KhmlCwNAtwSazeZQEwHd584bqs',
    appId: '1:804475636661:web:5bd0ac704a259ac967a7fc',
    messagingSenderId: '804475636661',
    projectId: 'apd-junior',
    authDomain: 'apd-junior.firebaseapp.com',
    storageBucket: 'apd-junior.firebasestorage.app',
    measurementId: 'G-ZSKBNXT7TN',
  );
}
